/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VOID = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int RETURN = 10;
  /** RegularExpression Id. */
  int PRINTIO = 11;
  /** RegularExpression Id. */
  int LET = 12;
  /** RegularExpression Id. */
  int DEF = 13;
  /** RegularExpression Id. */
  int FLOAT = 14;
  /** RegularExpression Id. */
  int BOOL = 15;
  /** RegularExpression Id. */
  int READIO = 16;
  /** RegularExpression Id. */
  int ACHAVES = 17;
  /** RegularExpression Id. */
  int FCHAVES = 18;
  /** RegularExpression Id. */
  int APARENTESES = 19;
  /** RegularExpression Id. */
  int FPARENTESES = 20;
  /** RegularExpression Id. */
  int VIRGULA = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 24;
  /** RegularExpression Id. */
  int ATR = 25;
  /** RegularExpression Id. */
  int SOMA = 26;
  /** RegularExpression Id. */
  int SUB = 27;
  /** RegularExpression Id. */
  int MULT = 28;
  /** RegularExpression Id. */
  int DIV = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int OR = 31;
  /** RegularExpression Id. */
  int MENOR = 32;
  /** RegularExpression Id. */
  int MAIOR = 33;
  /** RegularExpression Id. */
  int IGUAL = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"void\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"return\"",
    "\"printIO\"",
    "\"let\"",
    "\"def\"",
    "\"float\"",
    "\"bool\"",
    "\"readIO\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"true\"",
    "\"false\"",
    "\";\"",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "<NUM>",
    "<ID>",
  };

}
